# Travis-CI Build for dynamitey 
# see travis-ci.org for details

language: csharp

install:
  - nuget restore CoAP.NET.2010.sln
  - nuget restore CoAP.NET40.2010.sln
script:
  - xbuild CoAP.NET.2010.sln /p:Configuration=Release
  - xbuild CoAP.NET.2010.sln /t:Clean
  - xbuild CoAP.NET40.2010.sln /p:Configuration=Release
